### ISSUE TITLE
Error when i try unpack efd archive.

### ISSUE THREAD

**Issue by kostakoff** [Infactum/onec_dtools#3]
`Last login: Sun Dec 17 10:47:14 on ttys000
MacBook-Pro-eret1k:~ eret1k$ cd /Users/eret1k/Desktop/onec_dtools-master/examples
MacBook-Pro-eret1k:examples eret1k$ python ./efd.py /Users/eret1k/Desktop/onec_dtools-master/tests/fixtures/Platform8Demo/1cv8.efd /Users/eret1k/Desktop/onec_dtools-master/tests/fixtures/Platform8Demo/
Traceback (most recent call last):
  File "./efd.py", line 25, in <module>
    sys.exit(main())
  File "./efd.py", line 22, in main
    supply_reader.unpack(args.output_path)
  File "./onec_dtools/supply_reader.py", line 133, in unpack
    timestamp = mtime.timestamp()
AttributeError: 'datetime.datetime' object has no attribute 'timestamp'
MacBook-Pro-eret1k:examples eret1k$ `

Can you fix it?

**Comment by Infactum** [comment]
You are probably using python2. Python 3.4+ is required for onec_dtools to work.
