### ISSUE TITLE
efd.py error

### ISSUE THREAD

**Issue by pasha-zzz** [Infactum/onec_dtools#6]
Python 3.7.0

Traceback (most recent call last):
  File "efd.py", line 24, in <module>
    sys.exit(main())
  File "efd.py", line 20, in main
    supply_reader = onec_dtools.SupplyReader(f)
AttributeError: module 'onec_dtools' has no attribute 'SupplyReader'

**Comment by Infactum** [comment]
Не воспроизводится. Укажите больше деталей.
```
(dtools) λ python --version
Python 3.7.2

(dtools) λ pip list
Package     Version
----------- -------
onec-dtools 0.5.0
pip         18.1
setuptools  40.6.2

(dtools) λ python efd.py 1cv8.efd unpack/

(dtools) λ ls unpack\
1c
```

**Comment by pasha-zzz** [comment]
D:\Programs\CPython>python.exe --version
Python 3.7.0

D:\Programs\CPython\Scripts>pip list
Package      Version
------------ --------
altgraph     0.16.1
asn1crypto   0.24.0
cffi         1.11.5
cryptography 2.3
future       0.16.0
idna         2.7
macholib     1.10
onec-dtools  0.5.0
pefile       2018.8.8
pip          19.0.1
pycparser    2.18
pycryptodome 3.6.4
PyInstaller  3.3.1
pypiwin32    223
pywin32      223
setuptools   40.0.0
six          1.11.0
vboxapi      1.0

D:\Programs\CPython>python.exe efd.py 1cv8.efd unpack\
Traceback (most recent call last):
  File "efd.py", line 24, in <module>
    sys.exit(main())
  File "efd.py", line 20, in main
    supply_reader = onec_dtools.SupplyReader(f)
AttributeError: module 'onec_dtools' has no attribute 'SupplyReader'

**Comment by Infactum** [comment]
Нужный атрибут у модуля точно есть.
https://github.com/Infactum/onec_dtools/blob/99c0b394f51fbd4225735ab37068c2dae00fdc00/onec_dtools/__init__.py#L4
https://github.com/Infactum/onec_dtools/blob/99c0b394f51fbd4225735ab37068c2dae00fdc00/onec_dtools/supply_reader.py#L70

Попробуйте обновиться на актуальную версию питона и проверить работу в чистом venv окружении без лишних пакетов. Библиотеку перекачайте из pip.

**Comment by pasha-zzz** [comment]
Просто обновил питон на 3.7.2 и setuptools еще на всякий случай через pip. Сделал uninstall/install и все заработало.
